# shopify.app.toml
name = "jean-personal-shopper"
client_id = "c32e3e172b1edd86b736629282230533"
application_url = "https://b7cc-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app"
embedded = true

[
access_scopes
]
scopes = "write_products,read_products,write_customers,read_customers"

[
auth
]
redirect_urls = [
  "https://b7cc-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app/auth/callback",
  "https://b7cc-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app/auth/tokens",
  "https://b7cc-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app/gdpr/customers_data_request",
  "https://b7cc-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app/gdpr/customers_redact",
  "https://b7cc-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app/gdpr/shop_redact"
]

[
webhooks
]
api_version = "2024-01"

[
pos
]
embedded = false

[
build
]
dev_store_url = "jean-personalization.myshopify.com"
automatically_update_urls_on_dev = true
