# shopify.app.toml
name = "jean-personal-shopper"
client_id = "c32e3e172b1edd86b736629282230533"
application_url = "https://b8be-2601-246-4100-39f0-210e-5aee-1fa5-6071.ngrok-free.app"
embedded = true

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = [
  "https://b8be-2601-246-4100-39f0-210e-5aee-1fa5-6071.ngrok-free.app/auth/callback",
  "https://b8be-2601-246-4100-39f0-210e-5aee-1fa5-6071.ngrok-free.app/api/auth"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
dev_store_url = "jean-personalization.myshopify.com"