# shopify.web.toml
type = "frontend"
name = "jean-personal-shopper-web"

[commands]
dev = "npm run dev"
build = "npm run build"
start = "npm run start"

[configuration]
build.cmd = "npm run build"
build.path = "build"