# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jean-personal-shopper"
client_id = "c32e3e172b1edd86b736629282230533"
application_url = "https://irrigation-ar-australia-generators.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://irrigation-ar-australia-generators.trycloudflare.com/auth/callback",
  "https://irrigation-ar-australia-generators.trycloudflare.com/auth/shopify/callback",
  "https://irrigation-ar-australia-generators.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "jean-personalization.myshopify.com"
automatically_update_urls_on_dev = true
