# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
name = "jean-personal-shopper"
client_id = "c32e3e172b1edd86b736629282230533"
application_url = "https://865c-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_customers,read_customers"

[auth]
redirect_urls = [
  "https://865c-2601-246-4100-39f0-5847-9fbd-456e-cdf3.ngrok-free.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "jean-personalization.myshopify.com"